spring:
  application:
    name: Routing-Service

info:
  component: Zuul Server

server:
  port: 9500

zuul:
  ignored-services: "*"
  routes:
    integration-service: 
      path: /pruebaSpring/**
      service-id: integration-service
  
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka